workspace:
  base: /app
  path: .

pipeline:
  build-3.7.1:
    image: python:3.7.1
    commands:
      - pip install flake8
      - pip install -e .
      - flake8
  pypi-publish:
    image: python:2.7.14
    secrets: [username, password]
    commands:
      - git fetch --tags
      - pip install twine
      - python setup.py sdist
      - twine upload dist/django-realtime-admin-${DRONE_TAG}.zip -u $username -p $password
    when:
      event: tag
